//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:49:25 PM CAT 
//


package za.co.nupay.xml.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NtwrkRpns" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}NetworkResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "ntwrkRpns"
})
public class Document {

    @XmlElement(name = "NtwrkRpns", required = true)
    protected NetworkResponse ntwrkRpns;

    /**
     * Gets the value of the ntwrkRpns property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkResponse }
     *     
     */
    public NetworkResponse getNtwrkRpns() {
        return ntwrkRpns;
    }

    /**
     * Sets the value of the ntwrkRpns property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkResponse }
     *     
     */
    public void setNtwrkRpns(NetworkResponse value) {
        this.ntwrkRpns = value;
    }

}
