//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:49:25 PM CAT 
//


package za.co.nupay.xml.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for NetworkResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="From" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}MemberId"/>
 *         &lt;element name="To" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}MemberId"/>
 *         &lt;element name="TrDtTm" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}ISODateTime"/>
 *         &lt;element name="MsgTrcNbr" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}Numeric6"/>
 *         &lt;element name="RpnsCd" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}Max2Text"/>
 *         &lt;element name="NtwrkMnCd" type="{urn:bsva:std:tech:xsd:rltm.810.001.001.01}Numeric3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkResponse", propOrder = {
    "from",
    "to",
    "trDtTm",
    "msgTrcNbr",
    "rpnsCd",
    "ntwrkMnCd"
})
public class NetworkResponse {

    @XmlElement(name = "From", required = true)
    protected MemberId from;
    @XmlElement(name = "To", required = true)
    protected MemberId to;
    @XmlElement(name = "TrDtTm", required = true)
    protected XMLGregorianCalendar trDtTm;
    @XmlElement(name = "MsgTrcNbr")
    protected int msgTrcNbr;
    @XmlElement(name = "RpnsCd", required = true)
    protected String rpnsCd;
    @XmlElement(name = "NtwrkMnCd")
    protected int ntwrkMnCd;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link MemberId }
     *     
     */
    public MemberId getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberId }
     *     
     */
    public void setFrom(MemberId value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link MemberId }
     *     
     */
    public MemberId getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberId }
     *     
     */
    public void setTo(MemberId value) {
        this.to = value;
    }

    /**
     * Gets the value of the trDtTm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrDtTm() {
        return trDtTm;
    }

    /**
     * Sets the value of the trDtTm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrDtTm(XMLGregorianCalendar value) {
        this.trDtTm = value;
    }

    /**
     * Gets the value of the msgTrcNbr property.
     * 
     */
    public int getMsgTrcNbr() {
        return msgTrcNbr;
    }

    /**
     * Sets the value of the msgTrcNbr property.
     * 
     */
    public void setMsgTrcNbr(int value) {
        this.msgTrcNbr = value;
    }

    /**
     * Gets the value of the rpnsCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpnsCd() {
        return rpnsCd;
    }

    /**
     * Sets the value of the rpnsCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpnsCd(String value) {
        this.rpnsCd = value;
    }

    /**
     * Gets the value of the ntwrkMnCd property.
     * 
     */
    public int getNtwrkMnCd() {
        return ntwrkMnCd;
    }

    /**
     * Sets the value of the ntwrkMnCd property.
     * 
     */
    public void setNtwrkMnCd(int value) {
        this.ntwrkMnCd = value;
    }

}
